import { PricingSection } from "../agent-demo/pricing";
import { TestimonialCarousel } from "../agent-demo/carousel";
import { AgentShowcase } from "../AgentShowcase.client";
import { pricing, carousel } from "../agent-demo/generated";

export const metadata = {
  title: "Lab: agent showcase candidates",
  robots: { index: false },
};

const PRICING_PROMPT =
  "Build a pricing section with three plans using @loamui/core. Use native elements and the element styles for the type, a scoped rule with --loam-* tokens for the card anatomy, Card, Badge and Button for the parts, and mark the recommended plan with --loam-context: primary on its root. Do not add size, variant or colour props, and do not restyle LoamUI internals. Fetch https://loamui.com/llms.txt and use its rules for LoamUI in this project.";

const CAROUSEL_PROMPT =
  "Build a testimonial carousel using @loamui/core: a horizontally scrolling set of quote cards with previous/next buttons. Use native elements and the element styles for the type, CSS scroll-snap for the scrolling, a scoped rule with --loam-* tokens for the layout, and Card, Avatar and Button for the parts. Do not add size, variant or colour props, and do not restyle LoamUI internals. Fetch https://loamui.com/llms.txt and use its rules for LoamUI in this project.";

/** Temporary comparison page for choosing the homepage showcase. Not linked. */
export default function LabPage() {
  return (
    <main className="container" style={{ display: "grid", gap: "4rem", paddingBlock: "3rem" }}>
      <section>
        <span className="eyebrow">Candidate A</span>
        <h1>Pricing section</h1>
        <AgentShowcase
          skillCommand="npx skills add dangerfarms/loamui"
          skillNote="soon"
          prompt={PRICING_PROMPT}
          tsx={pricing.tsx}
          css={pricing.css}
          caption="Generated by Fable 5.1 from llms.txt alone, then stylelint --fix; otherwise unedited."
        >
          <PricingSection />
        </AgentShowcase>
      </section>
      <section>
        <span className="eyebrow">Candidate B</span>
        <h1>Testimonial carousel</h1>
        <AgentShowcase
          skillCommand="npx skills add dangerfarms/loamui"
          skillNote="soon"
          prompt={CAROUSEL_PROMPT}
          tsx={carousel.tsx}
          css={carousel.css}
          caption="Generated by Fable 5.1 from llms.txt alone, then stylelint --fix; otherwise unedited."
        >
          <TestimonialCarousel />
        </AgentShowcase>
      </section>
    </main>
  );
}
