import { PricingSection } from "../agent-demo/pricing";
import { TestimonialCarousel } from "../agent-demo/carousel";
import { EnvironmentsOverview } from "../agent-demo/environments";
import { RestaurantMenu } from "../agent-demo/menu";
import { AgentShowcase } from "../AgentShowcase.client";
import { pricing, carousel, environments, menu } from "../agent-demo/generated";

export const metadata = {
  title: "Lab: agent showcase candidates",
  robots: { index: false },
};

const PRICING_PROMPT =
  "Build a pricing section with three plans using @loamui/core. Use native elements and the element styles for the type, a scoped rule with --loam-* tokens for the card anatomy, Card, Badge and Button for the parts, and mark the recommended plan with --loam-context: primary on its root. Do not add size, variant or colour props, and do not restyle LoamUI internals. Fetch https://loamui.com/llms.txt and use its rules for LoamUI in this project.";

const ENVIRONMENTS_PROMPT =
  "Build an environments overview using @loamui/core: three cards for Production, Staging and Preview. Each card shows the environment name, a status badge (Healthy, Deploying, Checks failed), a short list of facts (last deploy, commit, URL) and one action button. Use native elements and the element styles for the type, a scoped rule with --loam-* tokens for the card anatomy, Card, Badge and Button for the parts, and declare each card's status with --loam-context on its root (success, warning, danger) so the badge and the button take the status colour. Do not add size, variant or colour props, and do not restyle LoamUI internals. Fetch https://loamui.com/llms.txt and use its rules for LoamUI in this project.";

const MENU_PROMPT =
  "Build a restaurant menu using @loamui/core: three cards for Starter, Main course and Dessert. Each card lists three dishes with a one-line description and a price, has one status badge (Vegetarian, Contains nuts, Sold out) and one action button. Use native elements and the element styles for the type, a scoped rule with --loam-* tokens for the card anatomy, Card, Badge and Button for the parts, and declare each card's status with --loam-context on its root (success, warning, danger) so the badge and the button take the status colour; the sold-out card's button is disabled. Do not add size, variant or colour props, and do not restyle LoamUI internals. Fetch https://loamui.com/llms.txt and use its rules for LoamUI in this project.";

const CAROUSEL_PROMPT =
  "Build a testimonial carousel using @loamui/core: a horizontally scrolling set of quote cards with previous/next buttons. Use native elements and the element styles for the type, CSS scroll-snap for the scrolling, a scoped rule with --loam-* tokens for the layout, and Card, Avatar and Button for the parts. Do not add size, variant or colour props, and do not restyle LoamUI internals. Fetch https://loamui.com/llms.txt and use its rules for LoamUI in this project.";

/** Temporary comparison page for choosing the homepage showcase. Not linked. */
export default function LabPage() {
  return (
    <main className="container" style={{ display: "grid", gap: "4rem", paddingBlock: "3rem" }}>
      <section>
        <span className="eyebrow">Candidate C</span>
        <h1>Environments overview</h1>
        <AgentShowcase
          skillCommand="npx skills add dangerfarms/loamui"
          prompt={ENVIRONMENTS_PROMPT}
          tsx={environments.tsx}
          css={environments.css}
          caption="Generated by Fable 5.1 from llms.txt and AGENTS.md alone, then stylelint --fix; otherwise unedited."
        >
          <EnvironmentsOverview />
        </AgentShowcase>
      </section>
      <section>
        <span className="eyebrow">Candidate D (Daniel's menu)</span>
        <h1>Restaurant menu</h1>
        <AgentShowcase
          skillCommand="npx skills add dangerfarms/loamui"
          prompt={MENU_PROMPT}
          tsx={menu.tsx}
          css={menu.css}
          caption="Generated by Fable 5.1 from llms.txt and AGENTS.md alone, then stylelint --fix; otherwise unedited."
        >
          <RestaurantMenu />
        </AgentShowcase>
      </section>
      <section>
        <span className="eyebrow">Candidate A</span>
        <h1>Pricing section</h1>
        <AgentShowcase
          skillCommand="npx skills add dangerfarms/loamui"
          prompt={PRICING_PROMPT}
          tsx={pricing.tsx}
          css={pricing.css}
          caption="Generated by Fable 5.1 from llms.txt alone, then stylelint --fix; otherwise unedited."
        >
          <PricingSection />
        </AgentShowcase>
      </section>
      <section>
        <span className="eyebrow">Candidate B</span>
        <h1>Testimonial carousel</h1>
        <AgentShowcase
          skillCommand="npx skills add dangerfarms/loamui"
          prompt={CAROUSEL_PROMPT}
          tsx={carousel.tsx}
          css={carousel.css}
          caption="Generated by Fable 5.1 from llms.txt alone, then stylelint --fix; otherwise unedited."
        >
          <TestimonialCarousel />
        </AgentShowcase>
      </section>
    </main>
  );
}
