/**
 * The examples registry, generated from the folders under src/examples.
 *
 * Every example is a folder, src/examples/<category>/<slug>/, holding
 * Example.tsx, example.css, meta.ts and example.test.tsx. This script
 * scans them and writes two modules:
 *
 *   src/examples/generated-meta.ts   — one entry per example: slug,
 *                                      category and meta. JSX-free, so the
 *                                      navigation and the markdown export
 *                                      can list examples without loading
 *                                      a single component or stylesheet.
 *   src/examples/generated.ts        — the same entries with the Example
 *                                      component, for the pages to render.
 *   src/examples/generated-source.ts — the raw text of Example.tsx and
 *                                      example.css per slug, read from
 *                                      disk, so the code a page shows is
 *                                      the code its preview runs. Kept
 *                                      apart so the index, which renders
 *                                      every preview, ships no source.
 *
 * Runs before dev and build (see package.json); `pnpm check:examples`
 * checks the folders themselves.
 */
import { existsSync, readFileSync, readdirSync, statSync, writeFileSync } from "node:fs";
import { execFileSync } from "node:child_process";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { EXAMPLE_CATEGORIES } from "../src/examples/categories.js";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const DIR = join(ROOT, "src", "examples");
const REQUIRED = ["Example.tsx", "example.css", "meta.ts", "example.test.tsx"];

interface Found {
  category: string;
  slug: string;
  order: number;
}

const listed = new Set(EXAMPLE_CATEGORIES.map((c) => c.slug));
const found: Found[] = [];
const problems: string[] = [];

for (const category of readdirSync(DIR)) {
  const categoryDir = join(DIR, category);
  if (!statSync(categoryDir).isDirectory()) continue;
  if (!listed.has(category)) {
    problems.push(`src/examples/${category}/ is not listed in src/examples/categories.ts`);
    continue;
  }
  for (const slug of readdirSync(categoryDir)) {
    const dir = join(categoryDir, slug);
    if (!statSync(dir).isDirectory()) continue;
    const missing = REQUIRED.filter((f) => !existsSync(join(dir, f)));
    if (missing.length) {
      problems.push(`src/examples/${category}/${slug}/ is missing ${missing.join(", ")}`);
      continue;
    }
    // The display order is meta.order (lower first), then the slug. Read
    // as text: meta.ts is JSX-free but importing it here would pull the
    // type module through tsx for every example on every dev start.
    const meta = readFileSync(join(dir, "meta.ts"), "utf8");
    const order = Number(meta.match(/\border:\s*(\d+)/)?.[1] ?? 1000);
    found.push({ category, slug, order });
  }
}

for (const c of EXAMPLE_CATEGORIES) {
  if (!existsSync(join(DIR, c.slug))) problems.push(`categories.ts lists "${c.slug}" but src/examples/${c.slug}/ does not exist`);
}

if (problems.length) {
  console.error(`build-examples: ${problems.length} problem(s)\n- ${problems.join("\n- ")}`);
  process.exit(1);
}

const categoryIndex = new Map(EXAMPLE_CATEGORIES.map((c, i) => [c.slug, i]));
found.sort(
  (a, b) =>
    categoryIndex.get(a.category)! - categoryIndex.get(b.category)! ||
    a.order - b.order ||
    a.slug.localeCompare(b.slug),
);

const HEADER = [
  "// Generated by scripts/build-examples.mts from the folders under src/examples.",
  "// Do not edit: add or change an example folder and rerun `pnpm dev` or `pnpm build`.",
  "",
];

const metaModule = [
  ...HEADER,
  'import type { ExampleMetaEntry } from "./types";',
  ...found.map(({ category, slug }, i) => `import { meta as meta${i} } from "./${category}/${slug}/meta";`),
  "",
  "/** Every example's identity and meta, in category order then display order. JSX-free. */",
  "export const EXAMPLE_META: ExampleMetaEntry[] = [",
  ...found.map(
    ({ category, slug }, i) =>
      `  { slug: ${JSON.stringify(slug)}, category: ${JSON.stringify(category)}, meta: meta${i} },`,
  ),
  "];",
  "",
];

const registry = [
  ...HEADER,
  'import type { ExampleEntry } from "./types";',
  'import { EXAMPLE_META } from "./generated-meta";',
  ...found.map(({ category, slug }, i) => `import Example${i} from "./${category}/${slug}/Example";`),
  "",
  "/** Every example with its component, in the same order as EXAMPLE_META. */",
  "export const EXAMPLES: ExampleEntry[] = [",
  ...found.map((_, i) => `  { ...EXAMPLE_META[${i}]!, Example: Example${i} },`),
  "];",
  "",
];

const source = [
  ...HEADER,
  'import type { ExampleSource } from "./types";',
  "",
  "/** The raw source of each example, by slug: exactly the files the preview renders. */",
  "export const EXAMPLE_SOURCE: Record<string, ExampleSource> = {",
  ...found.flatMap(({ category, slug }) => {
    const dir = join(DIR, category, slug);
    const tsx = readFileSync(join(dir, "Example.tsx"), "utf8");
    const css = readFileSync(join(dir, "example.css"), "utf8");
    return [`  ${JSON.stringify(slug)}: {`, `    tsx: ${JSON.stringify(tsx)},`, `    css: ${JSON.stringify(css)},`, "  },"];
  }),
  "};",
  "",
];

const files = { "generated-meta.ts": metaModule, "generated.ts": registry, "generated-source.ts": source };
for (const [name, lines] of Object.entries(files)) writeFileSync(join(DIR, name), lines.join("\n"));
// The repo's format gate covers generated files too.
execFileSync("npx", ["oxfmt", ...Object.keys(files).map((name) => join(DIR, name))], { stdio: "ignore" });
console.log(`build-examples: ${found.length} example(s) in ${listed.size} categories → src/examples/${Object.keys(files).join(", ")}`);
