// Drift gate for the published `loamui` agent skill (skills/loamui).
//
// A skill that lies is worse than no skill, so CI verifies:
//   1. references/ matches the docs source (regenerated by the docs export;
//      a stale committed copy fails);
//   2. every component the SKILL.md table names exists in the library;
//   3. every local link in SKILL.md resolves;
//   4. SKILL.md stays inside its context budget (it is read in full on every
//      LoamUI task — depth belongs in references/).
// Pass --urls to also check that each https://loamui.com link returns 200.
import { execSync } from "node:child_process";
import { existsSync, readFileSync, readdirSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const SKILL_DIR = join(ROOT, "skills", "loamui");
const SKILL = join(SKILL_DIR, "SKILL.md");
const COMPONENTS_DIR = join(ROOT, "packages", "core", "src", "components");
const BUDGET_CHARS = 16_000; // ≈ 4k tokens

const failures = [];
const fail = (msg) => failures.push(msg);

// 1. references in sync -----------------------------------------------------
execSync("npx tsx --tsconfig scripts/tsconfig.export.json scripts/export-markdown.mts", {
  cwd: join(ROOT, "apps", "docs"),
  stdio: "pipe",
});
const drift = execSync("git status --porcelain -- skills/loamui/references", { cwd: ROOT }).toString().trim();
if (drift) fail(`references/ is stale — commit the regenerated files:\n${drift}`);

// 2. named components exist ----------------------------------------------
const md = readFileSync(SKILL, "utf8");
const existing = new Set(readdirSync(COMPONENTS_DIR));
const table = md.split("## Components")[1]?.split("\n## ")[0] ?? "";
for (const row of table.split("\n").filter((l) => l.startsWith("| ") && !l.startsWith("| Category") && !l.startsWith("| ---"))) {
  const names = row.split("|")[2]?.split(",").map((s) => s.trim()).filter(Boolean) ?? [];
  for (const name of names) if (!existing.has(name)) fail(`SKILL.md names "${name}" but packages/core/src/components/${name} does not exist`);
}

// 3. local links resolve ----------------------------------------------------
for (const m of md.matchAll(/\]\((references\/[^)#]+)\)/g)) {
  if (!existsSync(join(SKILL_DIR, m[1]))) fail(`SKILL.md links to missing file ${m[1]}`);
}
for (const m of md.matchAll(/`(references\/[a-z/-]+\.md)`/g)) {
  if (!existsSync(join(SKILL_DIR, m[1]))) fail(`SKILL.md mentions missing file ${m[1]}`);
}

// 4. budget -----------------------------------------------------------------
if (md.length > BUDGET_CHARS)
  fail(`SKILL.md is ${md.length} chars; budget is ${BUDGET_CHARS} (≈4k tokens). Move depth into references/.`);

// optional: live URLs -------------------------------------------------------
if (process.argv.includes("--urls")) {
  const urls = [...new Set([...md.matchAll(/https:\/\/loamui\.com[^\s)>`]*/g)].map((m) => m[0]))];
  for (const url of urls) {
    const res = await fetch(url, { method: "HEAD" }).catch(() => null);
    if (!res || res.status !== 200) fail(`${url} → ${res ? res.status : "unreachable"}`);
  }
}

if (failures.length) {
  console.error(`check-skill: ${failures.length} problem(s)\n- ` + failures.join("\n- "));
  process.exit(1);
}
console.log(`check-skill: OK (${md.length} chars, ${existing.size} components, references in sync)`);
