// Generated by scripts/build-examples.mts from the folders under src/examples.
// Do not edit: add or change an example folder and rerun `pnpm dev` or `pnpm build`.

import { lazy, type ComponentType, type LazyExoticComponent } from "react";

/** Lazy identities stay stable; examples in a category share an import boundary. */
export const EXAMPLE_PREVIEWS: Record<string, LazyExoticComponent<ComponentType>> = {
  "hero-with-image": lazy(() =>
    import("./generated-preview-heroes").then((m) => ({ default: m.Example0 })),
  ),
  "hero-background-image": lazy(() =>
    import("./generated-preview-heroes").then((m) => ({ default: m.Example1 })),
  ),
  "banner-with-image": lazy(() =>
    import("./generated-preview-banners").then((m) => ({ default: m.Example2 })),
  ),
  "banner-background-image": lazy(() =>
    import("./generated-preview-banners").then((m) => ({ default: m.Example3 })),
  ),
  "article-card": lazy(() =>
    import("./generated-preview-cards").then((m) => ({ default: m.Example4 })),
  ),
  "profile-card": lazy(() =>
    import("./generated-preview-cards").then((m) => ({ default: m.Example5 })),
  ),
  "gallery-card": lazy(() =>
    import("./generated-preview-cards").then((m) => ({ default: m.Example6 })),
  ),
  "article-carousel": lazy(() =>
    import("./generated-preview-media").then((m) => ({ default: m.Example7 })),
  ),
  "image-comparison": lazy(() =>
    import("./generated-preview-media").then((m) => ({ default: m.Example8 })),
  ),
  "grid-asymmetric": lazy(() =>
    import("./generated-preview-grids").then((m) => ({ default: m.Example9 })),
  ),
  "grid-subgrid": lazy(() =>
    import("./generated-preview-grids").then((m) => ({ default: m.Example10 })),
  ),
  faq: lazy(() => import("./generated-preview-content").then((m) => ({ default: m.Example11 }))),
  timeline: lazy(() =>
    import("./generated-preview-content").then((m) => ({ default: m.Example12 })),
  ),
  "sign-in-with-errors": lazy(() =>
    import("./generated-preview-forms").then((m) => ({ default: m.Example13 })),
  ),
  "contact-us-with-details": lazy(() =>
    import("./generated-preview-forms").then((m) => ({ default: m.Example14 })),
  ),
};
