// Generated by scripts/build-examples.mts from the folders under src/examples.
// Do not edit: add or change an example folder and rerun `pnpm dev` or `pnpm build`.

export { default as Example122 } from "./faq/faq-simple/Example";
export { default as Example123 } from "./faq/faq-with-background/Example";
export { default as Example124 } from "./faq/faq-with-image/Example";
export { default as Example125 } from "./faq/faq-page-header/Example";
