// Generated by scripts/build-examples.mts from the folders under src/examples.
// Do not edit: add or change an example folder and rerun `pnpm dev` or `pnpm build`.

export { default as Example2 } from "./banners/banner-with-image/Example";
export { default as Example3 } from "./banners/banner-background-image/Example";
