// Generated by scripts/build-examples.mts from the folders under src/examples.
// Do not edit: add or change an example folder and rerun `pnpm dev` or `pnpm build`.

export { default as Example28 } from "./navigation/footer-with-columns/Example";
export { default as Example29 } from "./navigation/header-simple/Example";
export { default as Example30 } from "./navigation/header-with-search/Example";
export { default as Example31 } from "./navigation/footer-simple/Example";
export { default as Example32 } from "./navigation/mobile-nav/Example";
export { default as Example33 } from "./navigation/side-nav/Example";
export { default as Example34 } from "./navigation/side-nav-with-groups/Example";
export { default as Example35 } from "./navigation/table-of-contents/Example";
export { default as Example36 } from "./navigation/social-links/Example";
export { default as Example37 } from "./navigation/page-header/Example";
export { default as Example38 } from "./navigation/side-nav-two-sections/Example";
export { default as Example39 } from "./navigation/side-nav-rail/Example";
export { default as Example40 } from "./navigation/side-nav-with-search/Example";
export { default as Example41 } from "./navigation/side-nav-with-segmented-control/Example";
export { default as Example42 } from "./navigation/header-with-menus/Example";
export { default as Example43 } from "./navigation/header-mega-menu/Example";
export { default as Example44 } from "./navigation/header-with-tabs/Example";
export { default as Example45 } from "./navigation/footer-centered/Example";
export { default as Example46 } from "./navigation/footer-with-social/Example";
