// Generated by scripts/build-examples.mts from the folders under src/examples.
// Do not edit: add or change an example folder and rerun `pnpm dev` or `pnpm build`.

import type { ExampleEntry } from "./types";
import { EXAMPLE_META } from "./generated-meta";
import Example0 from "./page-sections/hero-with-image/Example";
import Example1 from "./page-sections/hero-centered/Example";
import Example2 from "./page-sections/call-to-action/Example";
import Example3 from "./page-sections/call-to-action-with-media/Example";
import Example4 from "./page-sections/banner/Example";
import Example5 from "./page-sections/banner-warning/Example";
import Example6 from "./page-sections/section-header/Example";
import Example7 from "./page-sections/feature-grid/Example";
import Example8 from "./page-sections/testimonial/Example";
import Example9 from "./page-sections/testimonial-carousel/Example";
import Example10 from "./page-sections/logo-wall/Example";
import Example11 from "./page-sections/gallery-lightbox/Example";
import Example12 from "./page-sections/image-comparison/Example";
import Example13 from "./page-sections/embed-video/Example";
import Example14 from "./page-sections/embed-map/Example";
import Example15 from "./page-sections/empty-state/Example";
import Example16 from "./page-sections/cookie-banner/Example";
import Example17 from "./page-sections/stepper-progress/Example";
import Example18 from "./page-sections/timeline/Example";
import Example19 from "./page-sections/person-grid/Example";
import Example20 from "./page-sections/hero-background-image/Example";
import Example21 from "./page-sections/hero-content-left/Example";
import Example22 from "./page-sections/hero-with-bullets/Example";
import Example23 from "./page-sections/features-with-cards/Example";
import Example24 from "./page-sections/features-with-title/Example";
import Example25 from "./page-sections/contact-us-with-details/Example";
import Example26 from "./page-sections/email-banner/Example";
import Example27 from "./page-sections/banner-with-image/Example";
import Example28 from "./navigation/footer-with-columns/Example";
import Example29 from "./navigation/header-simple/Example";
import Example30 from "./navigation/header-with-search/Example";
import Example31 from "./navigation/footer-simple/Example";
import Example32 from "./navigation/mobile-nav/Example";
import Example33 from "./navigation/side-nav/Example";
import Example34 from "./navigation/side-nav-with-groups/Example";
import Example35 from "./navigation/table-of-contents/Example";
import Example36 from "./navigation/social-links/Example";
import Example37 from "./navigation/page-header/Example";
import Example38 from "./navigation/side-nav-two-sections/Example";
import Example39 from "./navigation/side-nav-rail/Example";
import Example40 from "./navigation/side-nav-with-search/Example";
import Example41 from "./navigation/side-nav-with-segmented-control/Example";
import Example42 from "./navigation/header-with-menus/Example";
import Example43 from "./navigation/header-mega-menu/Example";
import Example44 from "./navigation/header-with-tabs/Example";
import Example45 from "./navigation/footer-centered/Example";
import Example46 from "./navigation/footer-with-social/Example";
import Example47 from "./forms/sign-in/Example";
import Example48 from "./forms/sign-up/Example";
import Example49 from "./forms/forgot-password/Example";
import Example50 from "./forms/sign-in-with-errors/Example";
import Example51 from "./forms/contact-form/Example";
import Example52 from "./forms/address-fields/Example";
import Example53 from "./forms/settings-rows/Example";
import Example54 from "./forms/password-strength/Example";
import Example55 from "./forms/choice-cards-radio/Example";
import Example56 from "./forms/choice-cards-checkbox/Example";
import Example57 from "./forms/scheme-toggle/Example";
import Example58 from "./forms/inline-search-form/Example";
import Example59 from "./forms/autocomplete-async/Example";
import Example60 from "./forms/floating-label/Example";
import Example61 from "./forms/number-with-currency/Example";
import Example62 from "./forms/forgot-password-on-label/Example";
import Example63 from "./forms/input-with-tooltip/Example";
import Example64 from "./forms/input-validation/Example";
import Example65 from "./forms/input-with-button/Example";
import Example66 from "./forms/language-picker/Example";
import Example67 from "./forms/dropzone/Example";
import Example68 from "./data-display/stats-grid/Example";
import Example69 from "./data-display/stat-with-trend/Example";
import Example70 from "./data-display/summary-list/Example";
import Example71 from "./data-display/task-list/Example";
import Example72 from "./data-display/contact-details/Example";
import Example73 from "./data-display/table-sortable/Example";
import Example74 from "./data-display/stats-with-controls/Example";
import Example75 from "./data-display/stats-with-diff/Example";
import Example76 from "./data-display/grouped-stats/Example";
import Example77 from "./data-display/stats-with-segments/Example";
import Example78 from "./data-display/table-reviews/Example";
import Example79 from "./data-display/table-sticky-header/Example";
import Example80 from "./data-display/table-with-selection/Example";
import Example81 from "./app-cards/card-actions-grid/Example";
import Example82 from "./app-cards/card-with-badges/Example";
import Example83 from "./app-cards/card-with-stats/Example";
import Example84 from "./app-cards/card-icon-features/Example";
import Example85 from "./app-cards/stats-card-progress/Example";
import Example86 from "./app-cards/card-with-switches/Example";
import Example87 from "./app-cards/tasks-card/Example";
import Example88 from "./users/user-menu/Example";
import Example89 from "./users/user-button/Example";
import Example90 from "./users/user-card/Example";
import Example91 from "./users/user-info-with-icons/Example";
import Example92 from "./users/users-table/Example";
import Example93 from "./users/users-table-with-roles/Example";
import Example94 from "./users/users-grid/Example";
import Example95 from "./blog/article-card/Example";
import Example96 from "./blog/article-cards-grid/Example";
import Example97 from "./blog/article-header/Example";
import Example98 from "./blog/byline/Example";
import Example99 from "./blog/comment/Example";
import Example100 from "./blog/comment-thread/Example";
import Example101 from "./blog/tag-list/Example";
import Example102 from "./blog/article-card-footer/Example";
import Example103 from "./blog/card-background-image/Example";
import Example104 from "./blog/vertical-article-card/Example";
import Example105 from "./blog/comment-html/Example";
import Example106 from "./commerce/product-card/Example";
import Example107 from "./commerce/product-grid/Example";
import Example108 from "./commerce/cart-line/Example";
import Example109 from "./commerce/mini-basket/Example";
import Example110 from "./commerce/order-summary/Example";
import Example111 from "./commerce/pricing-table/Example";
import Example112 from "./buttons/copy-to-clipboard/Example";
import Example113 from "./buttons/button-with-menu/Example";
import Example114 from "./buttons/button-with-progress/Example";
import Example115 from "./buttons/social-buttons/Example";
import Example116 from "./buttons/split-button/Example";
import Example117 from "./sliders/slider-with-marks/Example";
import Example118 from "./sliders/slider-with-output/Example";
import Example119 from "./sliders/number-input-with-slider/Example";
import Example120 from "./carousels/carousel-with-cards/Example";
import Example121 from "./carousels/card-with-carousel/Example";
import Example122 from "./faq/faq-simple/Example";
import Example123 from "./faq/faq-with-background/Example";
import Example124 from "./faq/faq-with-image/Example";
import Example125 from "./faq/faq-page-header/Example";
import Example126 from "./grids/grid-asymmetric/Example";
import Example127 from "./grids/grid-leading-item/Example";
import Example128 from "./grids/grid-subgrid/Example";
import Example129 from "./errors/error-404/Example";
import Example130 from "./errors/error-500/Example";
import Example131 from "./errors/error-404-image/Example";
import Example132 from "./errors/error-503/Example";

/** Every example with its component, in the same order as EXAMPLE_META. */
export const EXAMPLES: ExampleEntry[] = [
  { ...EXAMPLE_META[0]!, Example: Example0 },
  { ...EXAMPLE_META[1]!, Example: Example1 },
  { ...EXAMPLE_META[2]!, Example: Example2 },
  { ...EXAMPLE_META[3]!, Example: Example3 },
  { ...EXAMPLE_META[4]!, Example: Example4 },
  { ...EXAMPLE_META[5]!, Example: Example5 },
  { ...EXAMPLE_META[6]!, Example: Example6 },
  { ...EXAMPLE_META[7]!, Example: Example7 },
  { ...EXAMPLE_META[8]!, Example: Example8 },
  { ...EXAMPLE_META[9]!, Example: Example9 },
  { ...EXAMPLE_META[10]!, Example: Example10 },
  { ...EXAMPLE_META[11]!, Example: Example11 },
  { ...EXAMPLE_META[12]!, Example: Example12 },
  { ...EXAMPLE_META[13]!, Example: Example13 },
  { ...EXAMPLE_META[14]!, Example: Example14 },
  { ...EXAMPLE_META[15]!, Example: Example15 },
  { ...EXAMPLE_META[16]!, Example: Example16 },
  { ...EXAMPLE_META[17]!, Example: Example17 },
  { ...EXAMPLE_META[18]!, Example: Example18 },
  { ...EXAMPLE_META[19]!, Example: Example19 },
  { ...EXAMPLE_META[20]!, Example: Example20 },
  { ...EXAMPLE_META[21]!, Example: Example21 },
  { ...EXAMPLE_META[22]!, Example: Example22 },
  { ...EXAMPLE_META[23]!, Example: Example23 },
  { ...EXAMPLE_META[24]!, Example: Example24 },
  { ...EXAMPLE_META[25]!, Example: Example25 },
  { ...EXAMPLE_META[26]!, Example: Example26 },
  { ...EXAMPLE_META[27]!, Example: Example27 },
  { ...EXAMPLE_META[28]!, Example: Example28 },
  { ...EXAMPLE_META[29]!, Example: Example29 },
  { ...EXAMPLE_META[30]!, Example: Example30 },
  { ...EXAMPLE_META[31]!, Example: Example31 },
  { ...EXAMPLE_META[32]!, Example: Example32 },
  { ...EXAMPLE_META[33]!, Example: Example33 },
  { ...EXAMPLE_META[34]!, Example: Example34 },
  { ...EXAMPLE_META[35]!, Example: Example35 },
  { ...EXAMPLE_META[36]!, Example: Example36 },
  { ...EXAMPLE_META[37]!, Example: Example37 },
  { ...EXAMPLE_META[38]!, Example: Example38 },
  { ...EXAMPLE_META[39]!, Example: Example39 },
  { ...EXAMPLE_META[40]!, Example: Example40 },
  { ...EXAMPLE_META[41]!, Example: Example41 },
  { ...EXAMPLE_META[42]!, Example: Example42 },
  { ...EXAMPLE_META[43]!, Example: Example43 },
  { ...EXAMPLE_META[44]!, Example: Example44 },
  { ...EXAMPLE_META[45]!, Example: Example45 },
  { ...EXAMPLE_META[46]!, Example: Example46 },
  { ...EXAMPLE_META[47]!, Example: Example47 },
  { ...EXAMPLE_META[48]!, Example: Example48 },
  { ...EXAMPLE_META[49]!, Example: Example49 },
  { ...EXAMPLE_META[50]!, Example: Example50 },
  { ...EXAMPLE_META[51]!, Example: Example51 },
  { ...EXAMPLE_META[52]!, Example: Example52 },
  { ...EXAMPLE_META[53]!, Example: Example53 },
  { ...EXAMPLE_META[54]!, Example: Example54 },
  { ...EXAMPLE_META[55]!, Example: Example55 },
  { ...EXAMPLE_META[56]!, Example: Example56 },
  { ...EXAMPLE_META[57]!, Example: Example57 },
  { ...EXAMPLE_META[58]!, Example: Example58 },
  { ...EXAMPLE_META[59]!, Example: Example59 },
  { ...EXAMPLE_META[60]!, Example: Example60 },
  { ...EXAMPLE_META[61]!, Example: Example61 },
  { ...EXAMPLE_META[62]!, Example: Example62 },
  { ...EXAMPLE_META[63]!, Example: Example63 },
  { ...EXAMPLE_META[64]!, Example: Example64 },
  { ...EXAMPLE_META[65]!, Example: Example65 },
  { ...EXAMPLE_META[66]!, Example: Example66 },
  { ...EXAMPLE_META[67]!, Example: Example67 },
  { ...EXAMPLE_META[68]!, Example: Example68 },
  { ...EXAMPLE_META[69]!, Example: Example69 },
  { ...EXAMPLE_META[70]!, Example: Example70 },
  { ...EXAMPLE_META[71]!, Example: Example71 },
  { ...EXAMPLE_META[72]!, Example: Example72 },
  { ...EXAMPLE_META[73]!, Example: Example73 },
  { ...EXAMPLE_META[74]!, Example: Example74 },
  { ...EXAMPLE_META[75]!, Example: Example75 },
  { ...EXAMPLE_META[76]!, Example: Example76 },
  { ...EXAMPLE_META[77]!, Example: Example77 },
  { ...EXAMPLE_META[78]!, Example: Example78 },
  { ...EXAMPLE_META[79]!, Example: Example79 },
  { ...EXAMPLE_META[80]!, Example: Example80 },
  { ...EXAMPLE_META[81]!, Example: Example81 },
  { ...EXAMPLE_META[82]!, Example: Example82 },
  { ...EXAMPLE_META[83]!, Example: Example83 },
  { ...EXAMPLE_META[84]!, Example: Example84 },
  { ...EXAMPLE_META[85]!, Example: Example85 },
  { ...EXAMPLE_META[86]!, Example: Example86 },
  { ...EXAMPLE_META[87]!, Example: Example87 },
  { ...EXAMPLE_META[88]!, Example: Example88 },
  { ...EXAMPLE_META[89]!, Example: Example89 },
  { ...EXAMPLE_META[90]!, Example: Example90 },
  { ...EXAMPLE_META[91]!, Example: Example91 },
  { ...EXAMPLE_META[92]!, Example: Example92 },
  { ...EXAMPLE_META[93]!, Example: Example93 },
  { ...EXAMPLE_META[94]!, Example: Example94 },
  { ...EXAMPLE_META[95]!, Example: Example95 },
  { ...EXAMPLE_META[96]!, Example: Example96 },
  { ...EXAMPLE_META[97]!, Example: Example97 },
  { ...EXAMPLE_META[98]!, Example: Example98 },
  { ...EXAMPLE_META[99]!, Example: Example99 },
  { ...EXAMPLE_META[100]!, Example: Example100 },
  { ...EXAMPLE_META[101]!, Example: Example101 },
  { ...EXAMPLE_META[102]!, Example: Example102 },
  { ...EXAMPLE_META[103]!, Example: Example103 },
  { ...EXAMPLE_META[104]!, Example: Example104 },
  { ...EXAMPLE_META[105]!, Example: Example105 },
  { ...EXAMPLE_META[106]!, Example: Example106 },
  { ...EXAMPLE_META[107]!, Example: Example107 },
  { ...EXAMPLE_META[108]!, Example: Example108 },
  { ...EXAMPLE_META[109]!, Example: Example109 },
  { ...EXAMPLE_META[110]!, Example: Example110 },
  { ...EXAMPLE_META[111]!, Example: Example111 },
  { ...EXAMPLE_META[112]!, Example: Example112 },
  { ...EXAMPLE_META[113]!, Example: Example113 },
  { ...EXAMPLE_META[114]!, Example: Example114 },
  { ...EXAMPLE_META[115]!, Example: Example115 },
  { ...EXAMPLE_META[116]!, Example: Example116 },
  { ...EXAMPLE_META[117]!, Example: Example117 },
  { ...EXAMPLE_META[118]!, Example: Example118 },
  { ...EXAMPLE_META[119]!, Example: Example119 },
  { ...EXAMPLE_META[120]!, Example: Example120 },
  { ...EXAMPLE_META[121]!, Example: Example121 },
  { ...EXAMPLE_META[122]!, Example: Example122 },
  { ...EXAMPLE_META[123]!, Example: Example123 },
  { ...EXAMPLE_META[124]!, Example: Example124 },
  { ...EXAMPLE_META[125]!, Example: Example125 },
  { ...EXAMPLE_META[126]!, Example: Example126 },
  { ...EXAMPLE_META[127]!, Example: Example127 },
  { ...EXAMPLE_META[128]!, Example: Example128 },
  { ...EXAMPLE_META[129]!, Example: Example129 },
  { ...EXAMPLE_META[130]!, Example: Example130 },
  { ...EXAMPLE_META[131]!, Example: Example131 },
  { ...EXAMPLE_META[132]!, Example: Example132 },
];
