// Generated by scripts/build-examples.mts from the folders under src/examples.
// Do not edit: add or change an example folder and rerun `pnpm dev` or `pnpm build`.

export { default as Example0 } from "./heroes/hero-with-image/Example";
export { default as Example1 } from "./heroes/hero-background-image/Example";
