// Generated by scripts/build-examples.mts from the folders under src/examples.
// Do not edit: add or change an example folder and rerun `pnpm dev` or `pnpm build`.

import type { ExampleEntry } from "./types";
import { EXAMPLE_META } from "./generated-meta";
import Example0 from "./heroes/hero-with-image/Example";
import Example1 from "./heroes/hero-background-image/Example";
import Example2 from "./banners/banner-with-image/Example";
import Example3 from "./banners/banner-background-image/Example";
import Example4 from "./cards/article-card/Example";
import Example5 from "./cards/profile-card/Example";
import Example6 from "./cards/gallery-card/Example";
import Example7 from "./media/article-carousel/Example";
import Example8 from "./media/image-comparison/Example";
import Example9 from "./grids/grid-asymmetric/Example";
import Example10 from "./grids/grid-subgrid/Example";
import Example11 from "./content/faq/Example";
import Example12 from "./content/timeline/Example";
import Example13 from "./forms/sign-in-with-errors/Example";
import Example14 from "./forms/contact-us-with-details/Example";

/** Every example with its component, in the same order as EXAMPLE_META. */
export const EXAMPLES: ExampleEntry[] = [
  { ...EXAMPLE_META[0]!, Example: Example0 },
  { ...EXAMPLE_META[1]!, Example: Example1 },
  { ...EXAMPLE_META[2]!, Example: Example2 },
  { ...EXAMPLE_META[3]!, Example: Example3 },
  { ...EXAMPLE_META[4]!, Example: Example4 },
  { ...EXAMPLE_META[5]!, Example: Example5 },
  { ...EXAMPLE_META[6]!, Example: Example6 },
  { ...EXAMPLE_META[7]!, Example: Example7 },
  { ...EXAMPLE_META[8]!, Example: Example8 },
  { ...EXAMPLE_META[9]!, Example: Example9 },
  { ...EXAMPLE_META[10]!, Example: Example10 },
  { ...EXAMPLE_META[11]!, Example: Example11 },
  { ...EXAMPLE_META[12]!, Example: Example12 },
  { ...EXAMPLE_META[13]!, Example: Example13 },
  { ...EXAMPLE_META[14]!, Example: Example14 },
];
